language: go
go:
- 1.8.x
before_install:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- gometalinter --vendor --tests --disable=gotype --deadline 3m ./...
before_deploy:
- >
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    env GOOS=darwin GOARCH=amd64 go build -o "./corkboard_mac" ./cmd/corkboard;
    env GOOS=darwin GOARCH=386 go build -o "./corkboard_mac_x86" ./cmd/corkboard;
    env GOOS=linux GOARCH=amd64 go build -o "./corkboard_linux" ./cmd/corkboard;
    env GOOS=linux GOARCH=386 go build -o "./corkboard_linux_x86" ./cmd/corkboard;
    env GOOS=windows GOARCH=amd64 go build -o "./corkboard.exe" ./cmd/corkboard;
    env GOOS=windows GOARCH=386 go build -o "./corkboard_x86.exe" ./cmd/corkboard;
    cp "./corkboard_linux" "./deploy/corkboard";
    tar -czvf "corkboard-${TRAVIS_TAG}.tar.gz" -C deploy .;
    if [ -d compressed ]; then rm -r compressed; fi;
    mkdir compressed;
    mv corkboard-${TRAVIS_TAG}.tar.gz ./compressed;
  fi
deploy:
- provider: s3
  access_key_id: AKIAI6J3DLDG65WB423Q
  secret_access_key:
    secure: fF4JB1ZeuWWLSmOT/HaLLSinsaN0wsiIJLhiRHjs4XZbGZ1+9brz9JVOwwxH2HY0UYdmw9QUAoHUuCldAieBxag0yOLBXQ8BraVZiWGpCdIwe5HKEPCr8VVLMEFprJdaR/KfysdN3e/ESpteju6ssSi9nJLu67bgKgbySlBXc0qm8YDPqw80qw+klGvJ1wXx2S75vcZ2Cjv92ZaDKKVgEznKtZpZL3uxm4Cw1QwMH15+WYTbi0nDJubzNWRe/rxU11SjjOevoCdkBXhjUgAqkW6upwEha/E8SRUPHj34amW1lrxWxiOAbaKGBuUF8B3E4YBeh39anU15glszu3JbNT2ozyV5IZMzNMZ/Oy3wAmsJA+PAYbXIeqrmM0gihxymhV3B6qLStpQiJ3wD5N0eksFtYG4E0l3Yft3FgzNmNJUzF20T87ee8lDoRq7ystIDnGfdvJ+3i68DGe86hQrzrFPeiPe4PBEH+R3TuCWpylqBDyERbemFb5PYbP9CLKm2V9VOM2wdfOvnvHVAcjAWOnDh/3bH0xcW++jtaA4sfTotFjzpXt61dDs4uIJ8pkV5Ysxwd+dc4DkiRSeCZlJOaMz/k0iUeN5cBrY4DkIUa0l7n9Ue3kSvv6MKAnKxR6WPbquOfkuWiDfxUyjfCDH7kfv35PGaIDYkV+cYN2HojqE=
  bucket: corkboard.t.ac.st
  upload-dir: builds
  skip_cleanup: true
  local_dir: ${TRAVIS_BUILD_DIR}/compressed
  on:
    repo: acstech/corkboard
    branch: master
    tags: true
- provider: codedeploy
  access_key_id: AKIAI6J3DLDG65WB423Q
  secret_access_key:
    secure: fF4JB1ZeuWWLSmOT/HaLLSinsaN0wsiIJLhiRHjs4XZbGZ1+9brz9JVOwwxH2HY0UYdmw9QUAoHUuCldAieBxag0yOLBXQ8BraVZiWGpCdIwe5HKEPCr8VVLMEFprJdaR/KfysdN3e/ESpteju6ssSi9nJLu67bgKgbySlBXc0qm8YDPqw80qw+klGvJ1wXx2S75vcZ2Cjv92ZaDKKVgEznKtZpZL3uxm4Cw1QwMH15+WYTbi0nDJubzNWRe/rxU11SjjOevoCdkBXhjUgAqkW6upwEha/E8SRUPHj34amW1lrxWxiOAbaKGBuUF8B3E4YBeh39anU15glszu3JbNT2ozyV5IZMzNMZ/Oy3wAmsJA+PAYbXIeqrmM0gihxymhV3B6qLStpQiJ3wD5N0eksFtYG4E0l3Yft3FgzNmNJUzF20T87ee8lDoRq7ystIDnGfdvJ+3i68DGe86hQrzrFPeiPe4PBEH+R3TuCWpylqBDyERbemFb5PYbP9CLKm2V9VOM2wdfOvnvHVAcjAWOnDh/3bH0xcW++jtaA4sfTotFjzpXt61dDs4uIJ8pkV5Ysxwd+dc4DkiRSeCZlJOaMz/k0iUeN5cBrY4DkIUa0l7n9Ue3kSvv6MKAnKxR6WPbquOfkuWiDfxUyjfCDH7kfv35PGaIDYkV+cYN2HojqE=
  bucket: corkboard.t.ac.st
  application: corkboard
  key: builds/corkboard-${TRAVIS_TAG}.tar.gz
  bundle_type: tgz
  deployment_group: testing
  skip_cleanup: true
  on:
    repo: acstech/corkboard
    branch: master
    tags: true
- provider: releases
  api_key:
    secure: lOarF7u3UvCkarR370bK5kHoXsTZuBj7j7txmbddcKsOVoNZCz3cj88RDvNT+oaC6AltVAY33O8dTg+5zHV3rl3VWlNUBBIjLhkiTR3cQUh7XcuO9g5xjk6eegkEdcrIPpgRC+vdCKBkHz6sB25aA4encVxIhZcAcWfcYxqtCOok1R8eFHDxB0nG5IBWdZfYeb/TaZZPiM3KsQrmZ3spqPxVKgIJCBO3wEypsOCEBtgnOyl78/3YRduSfZMrQ+Jd+REFocV94TO08F4+e9fzBLGbThyeX2NxzmQUbW8XkqDV69yPwjFlmOeZWoLjUtsB1mjDR2nfupMPN8lg3UrZcj4HEhvDfH7Ud+a5r0bh/xr/7DqRCVzJw5ocSaDaP3pZtj5g/IaPXivpfsxEltzjpIMm5azKo6QUIHrqTFvfKhe7iUEnacyO1naQ/otFii/S1L8oC3zuVLtgU+rzhhTWlRNKy4t3RRyRUQs4oQZXE2/vt/KLXWhCU3tWudKbfdEyL/uBCfwa3KpwxTkKITCrO+ZCgQMzeXggCMSnDkog8Y074vMdmzuiPtczaTS5InRlLE6ySsRbQscTGn3YaIW2fawvepB5OydixOdVFC+udjHZfk61zkTafD76OFgT6WHYhf3MX07gu3BgyFxZ6kB/6szMJlRtIkfDdXn3mtjqhiY=
  file:
    - corkboard_mac
    - corkboard_mac_x86
    - corkboard_linux
    - corkboard_linux_x86
    - corkboard.exe
    - corkboard_x86.exe
  skip_cleanup: true
  on:
    repo: acstech/corkboard
    branch: master
    tags: true
